### ISSUE TITLE
a bug in 0.0.48 can't shutdown

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#577]
on 0.0.48, on jupyter notebook -> kernel-> 'shutdown kernel' button after pressed, nothing happen to the pods . but on 0.0.47 and below no issue.  can help to check. I think is a bug

**Comment by pdambrauskas** [comment]
Hello, thangs for reporting. The problem is caused due to changes on Kubernetes client library, that we are using.
We are trying to fix it, in the meantime you can switch back to 0.0.47

**Comment by pdambrauskas** [comment]
Workaround for the problem:
Add this env variable to the lighter deployment:
```
...
    spec:
      containers:
      - env:
        - name: KUBERNETES_TLS_VERSIONS
          value: TLSv1.2
...
```

We'll release an updated version with this value as default
